#!/bin/bash -e
# Smart gate run script
VALID_USER="pi"

if [ $(whoami) != $VALID_USER ]
then
    echo "$0: This should only be run as the \"$VALID_USER\" user." 1>&2
    exit 1
fi

cd /home/${VALID_USER}/smart-gate/
source venv/bin/activate
flock -nE 0 -x ~/gate.lock python rpi_src/main.py
